"""Write skill-update proposals to /data/staging/pending/skill-updates/.

CRITICAL: This module NEVER touches /data/mirror/ or any live skill file.
All output goes only to STAGING_PENDING_DIR/skill-updates/.
Human approval via approval-ui is required before any skill is modified.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

import structlog

from .config import settings

log = structlog.get_logger(__name__)

_SAFE_ID = re.compile(r"^[a-zA-Z0-9_-]+$")


def _staging_dir() -> Path:
    """Return the skill-updates staging directory, creating it if needed."""
    base = Path(settings.STAGING_PENDING_DIR)
    target = base / "skill-updates"
    target.mkdir(parents=True, exist_ok=True)
    return target


def write_skill_proposals(
    dept_id: str,
    agent_id: str,
    proposals: list[dict],
) -> list[str]:
    """Write each skill proposal as a separate markdown file in staging.

    Returns list of written file paths.
    Never raises — logs errors and continues.
    """
    if not proposals:
        return []

    if not _SAFE_ID.match(dept_id) or not _SAFE_ID.match(agent_id):
        log.error("skill_proposal_rejected_unsafe_id", dept=dept_id, agent=agent_id)
        return []

    written: list[str] = []
    staging = _staging_dir()
    now = datetime.now(tz=timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    ts_str = now.strftime("%Y%m%dT%H%M%SZ")

    for i, proposal in enumerate(proposals):
        skill_path = str(proposal.get("skill_path", f"skills/{dept_id}/")).strip()
        trigger = str(proposal.get("trigger", "unspecified")).strip()
        evidence = proposal.get("evidence", {})
        count = int(evidence.get("count", 0))
        avg_signal = float(evidence.get("avg_signal", 0.0))

        fname = f"{date_str}_{dept_id}_{agent_id}_{i:02d}_{ts_str}.md"
        fpath = staging / fname

        content = (
            f"---\n"
            f"type: skill-update-proposal\n"
            f"status: pending\n"
            f"dept: {dept_id}\n"
            f"agent: {agent_id}\n"
            f"created_at: {now.isoformat()}\n"
            f"---\n\n"
            f"# Skill Update Proposal — {agent_id} ({dept_id})\n\n"
            f"**Date:** {date_str}  \n"
            f"**Skill file:** `{skill_path}`  \n\n"
            f"## Trigger\n\n"
            f"{trigger}\n\n"
            f"## Evidence\n\n"
            f"- Interactions in window: {count}\n"
            f"- Average approval signal: {avg_signal:.3f} "
            f"(threshold < {settings.SIGNAL_THRESHOLD})\n\n"
            f"## Action Required\n\n"
            f"A human reviewer must open `{skill_path}` and decide whether to:\n\n"
            f"1. Update the skill's domain knowledge or retrieval instructions to reduce\n"
            f"   the pattern of low-signal proposals.\n"
            f"2. Reject this proposal if the pattern is expected.\n\n"
            f"> This file was auto-generated by the reflection engine.\n"
            f"> **Do not edit live skill files directly — use the approval-ui.**\n"
        )

        try:
            fpath.write_text(content, encoding="utf-8")
            written.append(str(fpath))
            log.info(
                "skill_proposal_written",
                path=str(fpath),
                dept=dept_id,
                agent=agent_id,
                trigger=trigger[:80],
                count=count,
                avg_signal=avg_signal,
            )
        except OSError:
            log.exception("skill_proposal_write_failed", path=str(fpath))

    return written
